name: Rust Project CI
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: ['master']

env:
  RUSTFLAGS: "-Dwarnings" # deny warnings

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Clippy Check
        run: cargo clippy

